my_django_project/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from niunius import views as v
from niunius.admin import admin_site
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("myadmin/", admin_site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", v.HomeView.as_view(), name="home"),
    path("logout/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path(
        "zmiana-hasla/",
        v.PasswordsChangeView.as_view(
            template_name="registration/change_password.html"
        ),
        name="change-password",
    ),
    path("register/", v.RegisterView.as_view(), name="register"),
    path("edytuj-profil/", v.UserChangeView.as_view(), name="edit-profile"),
    path("moje-zamowienia/", v.UserOrdersView.as_view(), name="user-orders"),
    path("o-klubie/", v.AboutView.as_view(), name="about"),
    path("kontakt/", v.ContactView.as_view(), name="contact"),
    path("warsztat/", v.CarServiceView.as_view(), name="car-service"),
    path("warsztat-wizyta/", v.BookVisitView.as_view(), name="book-visit"),
    path("blog/", v.BlogView.as_view(), name="blog"),
    path("blog/dodaj-artykul/", v.AddArticleView.as_view(), name="add-article"),
    path(
        "blog/zmien-artykul/<int:pk>/",
        v.UpdateArticleView.as_view(),
        name="update-article",
    ),
    path(
        "blog/artykul/<slug:slug>/",
        v.ArticleDetailView.as_view(),
        name="article-detail",
    ),
    path(
        "blog/artykul/<int:pk>/dodaj-komentarz/",
        v.AddCommentView.as_view(),
        name="add-comment",
    ),
    path("sklep/", v.ShopView.as_view(), name="shop"),
    path("sklep/szukaj/", v.SearchView.as_view(), name="search"),
    path("sklep/auto/<slug:slug>/", v.CarView.as_view(), name="car"),
    path("sklep/kategoria/<slug:slug>/", v.CategoryView.as_view(), name="category"),
    path("sklep/produkt/<slug:slug>/", v.ProductView.as_view(), name="product"),
    path("sklep/koszyk/", v.ShoppingCartView.as_view(), name="shopping-cart"),
    path(
        "sklep/koszyk/usun-produkt/<int:pk>/",
        v.DeleteItemView.as_view(),
        name="delete-item",
    ),
    path("sklep/zamowienie/", v.OrderView.as_view(), name="order"),
    path("sklep/zamowienie-gosc/", v.GuestOrderView.as_view(), name="guest-order"),
    path(
        "sklep/potwierdz-zamowienie/<int:pk>/",
        v.OrderConfirmationView.as_view(),
        name="confirm-order",
    ),
    path("sklep/potwierd-zakup/<int:pk>/", v.PurchaseView.as_view(), name="purchase"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

niunius/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MinValueValidator
from django.db import models
from django.utils.text import slugify


class Article(models.Model):
    """
    Title: title of the article
    Slug: slugified title
    Content: content of the article
    Added_by: user who created the article, User object
    Updated_by: user who made some changes, User object;
    user editing the article may be different from user who has created this article
    Added: date & time of creation
    Updated: date & time of update
    Like: how many times users pressed 'like' button for the article, default = 0
    Dislike: how many times users pressed 'dislike' button for the article, default = 0
    """

    title = models.CharField(max_length=128, verbose_name="Tytuł")
    slug = models.SlugField(unique=True, blank=True, max_length=128)
    content = models.TextField(verbose_name="Treść")
    added_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Dodane przez",
        related_name="creation",
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Zmienione przez",
        null=True,
        blank=True,
        related_name="update",
    )
    added = models.DateTimeField(auto_now_add=True, verbose_name="Dodano")
    updated = models.DateTimeField(
        auto_now=True, null=True, blank=True, verbose_name="Zmieniono"
    )
    like = models.IntegerField(default=0, verbose_name="Lubię")
    dislike = models.IntegerField(default=0, verbose_name="Nie lubię")

    class Meta:
        verbose_name = "Artykuł"
        verbose_name_plural = "Artykuły"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)


class ArticlePhoto(models.Model):
    """
    Article: Article object; each article can have many photos
    Photo: photo of the article
    """

    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, verbose_name="Artykuł"
    )
    photo = models.ImageField(upload_to="niunius/blog_img", verbose_name="Zdjęcie")

    class Meta:
        verbose_name = "Artykuł-zdjęcie"
        verbose_name_plural = "Artykuł-zdjęcia"

    def __str__(self):
        return self.photo.name


class ArticleComment(models.Model):
    """
    Article: Article object
    Text: text of the comment
    User: who has added the comment, User object
    Added: when the comment was added
    """

    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, verbose_name="Artykuł"
    )
    text = models.TextField(verbose_name="Tekst")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Użytkownik")
    added = models.DateTimeField(auto_now_add=True, verbose_name="Dodano")

    class Meta:
        verbose_name = "Artykuł-komentarz"
        verbose_name_plural = "Artykuł-komentarze"

    def __str__(self):
        return f"komentarz dodany {self.added} przez {self.user}"


class Car(models.Model):
    """
    Brand: brand of the car
    Model: model of the car brand, unique
    Slug: slugified name of the car; name is a concatenation of car brand and car model
    Image: image of the car
    """

    brand = models.CharField(max_length=64, verbose_name="Marka")
    model = models.CharField(max_length=64, unique=True, verbose_name="Model")
    slug = models.SlugField(unique=True, blank=True, max_length=128)
    image = models.ImageField(
        blank=True, upload_to="niunius/car_img/", verbose_name="Zdjęcie"
    )

    @property
    def name(self):
        return f"{self.brand} {self.model}"

    class Meta:
        verbose_name = "Auta"
        verbose_name_plural = "Auto"

    def __str__(self):
        return self.name

    def get_available_products(self):
        """Display only these products related to the car for which stock is not equal to 0."""
        return self.product_set.exclude(stock=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Car, self).save(*args, **kwargs)


class Category(models.Model):
    """
    Name: name of the category
    Slug: slugified name of the category
    """

    name = models.CharField(max_length=64, verbose_name="Nazwa")
    slug = models.SlugField(unique=True, blank=True, max_length=64)

    class Meta:
        verbose_name = "Kategoria"
        verbose_name_plural = "Kategorie"

    def __str__(self):
        return self.name

    def get_available_products(self):
        """Display only these products related to the category for which stock is not equal to 0."""
        return self.product_set.exclude(stock=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Product(models.Model):
    """
    Name: name of the product
    Slug: slugified name of the product
    Added: when the product was added
    Code: unique code of the product
    Stock: available quantity of the product
    Description: description of the product
    Price: price of the product
    Image: image of the product
    Cars: set of Car objects to which the product is related
    Categories: set of Category objects to which the product is related
    """

    name = models.CharField(max_length=128, verbose_name="Nazwa")
    slug = models.SlugField(unique=True, blank=True, max_length=128)
    added = models.DateTimeField(auto_now_add=True, verbose_name="Dodano")
    code = models.CharField(max_length=128, unique=True, verbose_name="Kod produktu")
    stock = models.IntegerField(
        validators=[MinValueValidator(0)], verbose_name="Dostępność"
    )
    description = models.TextField(verbose_name="Opis")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cena")
    image = models.ImageField(
        blank=True, upload_to="niunius/product_img/", verbose_name="Zdjęcie"
    )
    cars = models.ManyToManyField(Car, verbose_name="Pasuje do auta")
    categories = models.ManyToManyField(Category, verbose_name="Należy do kategorii")

    class Meta:
        verbose_name = "Produkt"
        verbose_name_plural = "Produkty"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)


class ShoppingCart(models.Model):
    """
    Is_ordered:
        False - when the shopping cart is created for logged-in users
        True - when the order related to the shopping cart is finalized, only for logged-in users
        Null - for anonymous users
    """

    is_ordered = models.BooleanField(null=True)

    class Meta:
        verbose_name = "Koszyk"
        verbose_name_plural = "Koszyki"

    def total(self):
        """Calculate the total value of the shopping cart, amount to pay."""
        return sum([item.value for item in self.cartitem_set.all()])

    def __str__(self):
        return f"Koszyk nr: {self.id}"


class CartItem(models.Model):
    """
    Product: related Product object
    Quantity: quantity of a given product in a given shopping cart
    Cart: related ShoppingCart object
    """

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name="Produkt"
    )
    quantity = models.IntegerField(
        verbose_name="Ilość", validators=[MinValueValidator(0)]
    )
    cart = models.ForeignKey(
        ShoppingCart, on_delete=models.CASCADE, verbose_name="Koszyk"
    )

    @property
    def value(self):
        return self.quantity * self.product.price

    class Meta:
        verbose_name = "W koszyku"
        verbose_name_plural = "W koszyku"

    def __str__(self):
        return f"{self.product.name}, {self.quantity} szt."


class Order(models.Model):
    """
    Cart: related ShoppingCart object
    Buyer: logged-in user who placed the order, can be null as orders by guests are allowed
    Guest_buyer_first_name:
        the first name of the buyer-guest who placed the order, can be null if buyer (logged-in user) exists
    Guest_buyer_last_name:
        the last name of the buyer-guest who placed the order, can be null if buyer (logged-in user) exists
    Guest_buyer_email:
        the e-mail the buyer-guest who placed the order, can be null if buyer (logged-in user) exists
    Address_city, Address_zipcode, Address_street, Address_country:
        details for the address of the buyer who placed the order
    Date: date & time of the order
    Delivery: delivery method chosen for the order
    Payment: payment method chosen for the order
    Paid: True if the order was paid for, False otherwise
    """

    cart = models.OneToOneField(ShoppingCart, on_delete=models.CASCADE)
    buyer = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        verbose_name="Klient - zalogowany użytkownik",
    )
    guest_buyer_first_name = models.CharField(
        max_length=64, null=True, verbose_name="Klient - Gość - imię"
    )
    guest_buyer_last_name = models.CharField(
        max_length=64, null=True, verbose_name="Klient - Gość - nazwisko"
    )
    guest_buyer_email = models.EmailField(
        null=True, verbose_name="Klient - Gość - email"
    )
    address_city = models.CharField(max_length=64, verbose_name="Miasto")
    address_zipcode = models.CharField(
        max_length=6,
        validators=[RegexValidator(regex=r"\d{2}-\d{3}")],
        verbose_name="Kod pocztowy",
    )
    address_street = models.CharField(max_length=64, verbose_name="Ulica")
    address_country = models.CharField(max_length=64, verbose_name="Kraj")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Data zamówienia")
    delivery = models.CharField(
        max_length=32,
        choices=[("Kurier", "Kurier"), ("Odbiór własny", "Odbiór własny")],

niunius/templates/niunius/about.html
{% extends "niunius/base.html" %}
{% load static %}
{% block background %}style="background-color: #e3dede"{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header" style="text-align: center">
      <strong>{{ article.title|upper }}</strong>
  </div>
  <div class="card-body">
    <div class="row">
        <div class="col">
                    <div id="image">
                        <img class="img-fluid img-thumbnail" src="{{ article.articlephoto_set.all.0.photo.url }}" alt="photo">
                    </div>
        </div>
        <div class="col">
            <p class="card-text">{{ article.content }}</p>
        </div>

    </div>
  </div>
</div>


{% endblock %}
{% block music %}{% endblock %}

niunius/templates/niunius/article_comment_form.html
{% extends "niunius/base.html" %}
{% block background %}style="background-color: #e3dede"{% endblock %}
{% block content %}
<div style="text-align: center">
    <h1>Dodaj komentarz</h1>
    <hr>
    <form method="post" action="{% url 'add-comment' article.pk %}">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}"><br>
    {% endif %}
        <input type="submit" class="btn btn-warning" value="zapisz">
    </form>
</div>
{% endblock %}
{% block music %}{% endblock %}

niunius/templates/niunius/article_form.html
{% extends "niunius/base.html" %}
{% block background %}style="background-color: #e3dede"{% endblock %}
{% block content %}
    <h2>Dodaj nowy artykuł</h2>
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
<div class="card">
  <div class="card-header">
      <strong>{{ form.title }}</strong>
  </div>
  <div class="card-body">
    <div class="row">
        <div class="col">
            <p class="card-text">{{ form.content }}</p>
        </div>
        <div class="col">
            {{ form.photos }}
            <div>
                <label for="id_photos" class="btn btn-warning">dodaj zdjęcia</label>
                <span id="files-count"></span><span>  </span><span id="files-text"></span>
            </div>
        </div>
    </div>
  </div>
</div>

    <input class="btn btn-warning" style="" type="submit" value="zapisz">

</form>

    <script>
    files_text=document.getElementById("files-text")
    files_count=document.getElementById("files-count")
    document.getElementById("id_photos").addEventListener("change", function() {
        files_count.innerHTML=this.files.length
        if (this.files.length === 1) {
            files_text.innerText = "plik"
        } else if (this.files.length === 2 || this.files.length === 3 || this.files.length === 4) {
            files_text.innerText = "pliki"
        } else {
            files_text.innerText = "plików"
        }
    });
    </script>

{% endblock %}
{% block music %}{% endblock %}

niunius/templates/niunius/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'niunius/img/favicon.png' %}"/>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/sticky-footer-navbar/">
    <link rel="stylesheet" href="{% static 'niunius/css/style.css' %}" />

    <title>Niuniuś</title>
</head>

<body {% block background %}{% endblock %}>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">NIUNIUŚ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% url 'about' as about %}
          {% url 'home' as home %}
          {% url 'blog' as blog %}
          {% url 'shop' as shop %}
          {% url 'car-service' as service %}
          {% url 'contact' as contact %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == about %}active{% endif %}" href="{% url 'about' %}">o klubie</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == blog %}active{% endif %}" href="{% url 'blog' %}">blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == shop %}active{% endif %}" href="{% url 'shop' %}">sklep</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == service %}active{% endif %}" href="{% url 'car-service' %}">warsztat</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == contact %}active{% endif %}" href="{% url 'contact' %}">kontakt</a>
        </li>
      </ul>

        {% if request.user.is_superuser%}
            <a target="_blank" class="btn btn-outline-warning" href="{% url 'admin:index' %}">admin</a>
        {% endif %}
    {% block auth %}
        {% if request.user.is_authenticated %}
            <a class="btn btn-outline-warning" href="{% url 'logout' %}">wyloguj się</a>
            <a class="btn btn-outline-warning" href="{% url 'edit-profile' %}">Twoje Konto</a>
        {% else %}
            <a class="btn btn-outline-warning" href="{% url 'login' %}?next={{ request.path }}">zaloguj się</a>
            <a class="btn btn-outline-warning" href="{% url 'register' %}?next={{ request.path }}">zarejestruj się</a>
        {% endif %}
    {% endblock %}

    </div>
  </div>
</nav>

<section class="p-5">
{% block content %}
<div class="text-center">
    <img src="{% static 'niunius/img/logo.jpg' %}" class="img-fluid" alt="logo">
</div>
{% endblock %}
</section>

<footer class="footer">
      <div class="container">
          {% block music %}
          <!--
          SURPRISE :-) Congratulations if you are reading this.
          If you uncomment the below code, you will hear a very special "home-made" piece of music.
          -->
          <!--
          <div>
            <audio loop controls>
                <source src="{% static 'niunius/music/song.m4a' %}" type="audio/mpeg">
            </audio>
            <small style="color: white">by Niuniuś Band :-)</small>
          </div>
          -->
          {% endblock music %}
      </div>
</footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="{% static 'niunius/js/app.js' %}"></script>
</body>
</html>

niunius/templates/niunius/blog.html
{% extends  "niunius/base.html" %}
{% block background %}style="background-color: #e3dede"{% endblock %}
{% block content %}
<div class="row">

    <div class="col-4"><h2>Artykuły na blogu</h2></div>
    <div class="col-1"></div>
    <div class="col-7"><h2>Ostatnio dodane</h2></div>

</div>

<div class="row p-2">

<div class="col-4">
    <ul>
        {% for article in page_obj %}
            <li class="p-3">
                <p style="display: inline"> {{ article.title }} </p>
                <a class="btn btn-secondary" style="float: right;" href="{% url 'article-detail' article.slug %}">szczegóły</a>
            </li>
        {% endfor %}
            <li class="p-3">
                <p style="display: inline"><a href="{% url 'add-article' %}">dodaj nowy artykuł</a></p>
            </li>
    </ul>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pierwsza</a>
            <a href="?page={{ page_obj.previous_page_number }}">poprzednia</a>
        {% endif %}

        <span class="current">
            Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">następna</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">ostatnia &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
<div class="col-1"></div>
<div class="col-7">
    <div id="carouselExampleControls" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
        {% for article in carousel_articles %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <div class="container" style="text-align: center">
                    <h5><a href="{% url 'article-detail' article.slug %}">{{ article.title }}</a></h5>
                </div>
                {% if article.articlephoto_set.all %}
                <div class="blog-img" id="image">
                    <img class="img-fit" src="{{ article.articlephoto_set.all.0.photo.url }}" alt="slide">
                </div >
                {% else %}
                <div class="blog-img" style="text-align: center; position: relative; background-color: lightgray">
                    <div class="container" style="position: absolute; top: 40%">
                        <p>Ten artykuł nie ma jeszcze zdjęć.</p>
                        <a class="btn btn-warning" href="{% url 'update-article' article.pk %}">Dodaj</a>
                    </div>
                </div>
                {% endif %}
            </div>
        {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only visually-hidden">Poprzednie</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only visually-hidden">Następne</span>
        </a>
    </div>
</div>
</div>
{% endblock %}
{% block music %}{% endblock %}

niunius/templates/niunius/car.html
{% extends "niunius/shop.html" %}
{% block title-shop %}{% endblock %}
{% block content-shop %}
<div class="col-7 p-3" style="position: relative">
    <h3>{{ car.name }}</h3>
    <hr>
    <div class="row p-2">
        <div class="col"  id="image">
            <img class="img-fluid" src="{{ car.image.url }}" alt="car">
        </div>
        <div class="col">
            <h5>Produkty:</h5>
            <ul>
            {% for product in car.get_available_products %}
                <li><a href="{% url 'product' product.slug %}">{{ product.name }}</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

niunius/templates/niunius/category.html
{% extends "niunius/shop.html" %}
{% block title-shop %}{% endblock %}
{% block content-shop %}
    <div class="col-7 p-3" style="position: relative">
    <h3>{{ category.name }}</h3>
    <hr>
    {% for product in category.get_available_products %}
        <p><a href="{% url 'product' product.slug %}">{{ product.name }}</a></p>
    {% endfor %}
    </div>
{% endblock %}

niunius/templates/niunius/guest_order_form.html
{% extends "niunius/shop.html" %}
{% block title-shop %}{% endblock %}
{% block content-shop %}
    <div class="col-7">
        <form method="post">{% csrf_token %}
        <div class="row">
            <div class="col-5">
                <div class="row p-3" style="border: solid #e3632d">
                    <h4>Dane kupującego</h4>
                    <p>Masz konto? <a href="{% url 'login' %}?next=/sklep/zamowienie/">Zaloguj się</a></p>
                    {% for field in guest_form %}
                    {{ field.label }}
                    {{ field }}
                        <br>
                    {% endfor %}
                </div>
                <br>
                <div class="row p-3" style="border: solid #e3632d">
                    <h4>Adres dostawy</h4>
                    {% for field in form %}
                    {{ field.label }}
                    {{ field }}
                        <br>
                    {% endfor %}
                </div>
            </div>
            <div class="col-1"></div>
            <div class="col-5">
                <div class="row p-3" style="border: solid #e3632d">
                    <h4>Sposób dostawy</h4>
                    {{ delivery_form.as_p }}
                </div>
                <br>
                <div class="row p-3" style="border: solid #e3632d">
                    <h4>Sposób płatności</h4>
                    {{ payment_form.as_p }}
                </div>
            </div>

        </div>
            <input  style="float: right" class="btn btn-warning" type="submit" value="Przejdź do podsumowania">
        </form>
    </div>

{% endblock %}

niunius/templates/niunius/order_confirmation.html
{% extends "niunius/shop.html" %}
{% block title-shop %}<h2>Zamówienie #{{ order.pk }} - podsumowanie</h2>{% endblock %}
{% block content-shop %}
    <div class="col-7 p-3">
    <div class="row">
        <div class="col-5">
            <div class="row p-3" style="border: solid #e3632d">

                <p>{% firstof order.buyer.first_name order.guest_buyer_first_name %}</p>
                <p>{% firstof order.buyer.last_name order.guest_buyer_last_name %}</p>
                <p>{% firstof order.buyer.email order.guest_buyer_email %}</p>
                <hr>
                <p>{{ order.address_street }}</p>
                <p>{{ order.address_zipcode }} {{ order.address_city }}</p>
                <p>{{ order.address_country }}</p>
                <hr>
                <p>{{ order.delivery }}</p>
                <hr>
                <p>{{ order.payment }}</p>
            </div>
        </div>
        <div class="col-1"></div>
        <div class="col-5 p-3" style="border: solid #e3632d">
            <ol>
                {% for i in items %}
                <li>{{ i.product.name }} {{ i.quantity }} szt. {{ i.value }} zł</li>
                {% endfor %}
            </ol>
            <br><br>
            <p>Razem do zapłaty: <strong>{{ order.cart.total }} zł</strong></p>
        </div>
    </div>
    <br>
    <a style="float: right" class="btn btn-warning" href="{% url 'purchase' order.pk %}">Potwierdź</a>
    </div>
{% endblock %}

niunius/templates/niunius/product.html
{% extends "niunius/shop.html" %}
{% block title-shop %}{% endblock %}
{% block content-shop %}
<style>
    input[type=number]::-webkit-inner-spin-button {
    opacity: 1
    }
</style>
<div class="col-7 p-3" style="position: relative">
    <h3>{{ product.name }}</h3>
    <hr>
    <div class="row p-2">
        <div class="col" id="image"><img class="img-fluid" src="{{ product.image.url }}" alt="product"></div>
        <div class="col">
            <p>Kod produktu: {{ product.code }}</p>
            <p>Cena: {{ product.price }} zł</p>
            <p>Dostępność: {{ product.stock }} szt.</p>
            <form method="post" action="">
                {% csrf_token %}
                <input style="width: 46px; height: 27px" type="number" step="1" min="1" max="{{ product.stock }}" name="qty" value="1">
                <input type="submit" value="Dodaj do koszyka">
            </form>
            <br><br>

            <h5>Opis:</h5>
                <p> {{ product.description }}</p>

            <h5>Pasuje do:</h5>
                <ul>
                {% for car in product.cars.all %}
                    <li><a href="{% url 'car' car.slug %}">{{ car.name }}</a></li>
                {% endfor %}
                </ul>
        </div>
    </div>
</div>
{% endblock  %}